# BOAZ 12기 1주차 과제 파이썬 기초 문법

- 원하는 함수가 기억이 안나면 [이곳](https://wikidocs.net/book/1)을 참고해주세요
- 자주 사용하는 함수는 기억하는 것이 좋지만 대부분 기억이 나지 않습니다
- 원하는 기능이 있는 함수를 구글링 하는 능력이 중요합니다
- 영어로 어떻게 검색해야 하는지 학습하는 것이 가장 좋습니다

#### 1. 자료형 문제
#### 1-1. Slice 기능을 이용해 'you need python'(모두 소문자로) 을 출력하세요. 

In [30]:
a = "Life is too short, You need Python"

In [31]:
a = a[-15:]
a.lower()

'you need python'

#### 1-2. 숫자와 나누는 수를 입력하면 나머지를 반환하는 함수 remainder를 작성하세요

In [32]:
def reminder(n, m):
    return n%m

In [33]:
reminder(5,3)

2

#### 1-2. 입력한 수의 평균을 반환하는 함수 mean을 작성하세요 (*args를 이용해보세요 !)

In [35]:
def mean(*args):
    return sum(args) / len(args)
    

In [36]:
print(mean(1,2,3),mean(1,2,3,4,5,6,7,8), sep = "\n")

2.0
4.5


#### 1-3. for와 range를 사용해서 0부터 9까지 중 홀수인 1, 3, 5, 7, 9만 odd_nums에 저장하고 출력하는 코드를 짜보세요. 

In [39]:
odd_nums = []

for i in range(0,10):
    if i % 2 != 0:
        odd_nums.append(i)
        
odd_nums
        

[1, 3, 5, 7, 9]

#### 1-4. 다음 리스트에서 생일만 리스트에 담는 함수 birth를 작성하세요

In [45]:
pin1 = " 930115-1234567"
pin2 = "990101- 2257262"
pin3 = "000327 - 1010209"
pin4 = "010101-2047219 "
pin5 = "9706091360217"
pin = [pin1, pin2, pin3, pin4, pin5]
print(pin)

[' 930115-1234567', '990101- 2257262', '000327 - 1010209', '010101-2047219 ', '9706091360217']


In [53]:
def birth(id_list):
    b_list = []
    for i in id_list:
        i = i.replace(" ","")
        i = i.replace("-","")
        b_list.append(i[2:6])
    return b_list          

In [54]:
birth(pin)

['0115', '0101', '0327', '0101', '0609']

#### 2. 함수 문제
#### 2-1.  if/ elif/ else문을 사용해서 2019년이 윤년인지 계산하는 코드를 짜보세요. 
- 윤년 계산법
    - 연도가 400으로 나누어 떨어지면 윤년입니다. 
    - 연도가 4로 나누어 떨어지면서 100으로 나누어 떨어지지 않으면 윤년입니다. 

In [60]:
year = 2019

if year % 400 == 0:
    print('{}년은 윤년입니다.'.format(year))
elif year % 4 == 0 & year % 100 != 0:
    print('{}년은 윤년입니다.'.format(year))
else:
    print('{}년은 윤년이 아닙니다.'.format(year))

2019년은 윤년이 아닙니다.


#### 2-2. 더하기, 빼기, 곱하기, 나누기 기능이 있는 클래스 Calculator를 작성하세요

In [67]:
class Calculator:
    def __init__(self,a,b):
        self.num1 = a
        self.num2 = b
    def add(self):
        return self.num1 + self.num2
    def subtract(self):
        return self.num1 - self.num2
    def multiply(self):
        return self.num1 * self.num2
    def divide(self):
        return round(self.num1 / self.num2,2)

In [68]:
Cal = Calculator(13,7)
print(Cal.add(),Cal.subtract(),Cal.multiply(),Cal.divide(), sep = "\n")

20
6
91
1.86


#### 2-3. 가위바위보 게임 만들기
다음 요구사항에 맞는 가위바위보 게임을 만들어보세요. 

In [99]:
# 사용자에게 '가위', '바위', '보'를 입력받으세요. 
import random 

play = True

while play:
    
    com = ["가위", "바위", "보"]
    result = ["draw.","win!", "lose.."]
    
    print("\"가위\", \"바위\",\"보\" 중 하나를 입력해주세요!\n(\"끝\"을 입력하면 종료합니다)\n")
    person = input("입력:")
    
    if person == "끝":
        print("\n종료합니다.")
        break
        
    elif not person in com:
        print("\n가위, 바위, 보 중에 선택하세요.\n")
        continue
    
    random_num = random.randrange(0,2)
    
    # 플레이어가 이긴경우 = (가위:보, 바위:가위, 보:바위)
    
    player_win = {"가위":"보","바위":"가위","보":"바위"}
    
    if person == com[random_num]:
        resultIndex = 0
    elif player_win[person] == com[random_num]:
        resultIndex = 1
    else:
        resultIndex = 2
        
    
    print("\n\nyou: {}".format(person))
    print("computer: {}\n".format(com[random_num]))
    print(result[resultIndex], "\n")
    
    



# 리스트에 가위, 바위, 보를 저장합니다. 

# 게임을 무한 반복합니다. 
# 사용자에게는 입력을 받고, 
# 컴퓨터는 랜덤하게 선택합니다. 

# 만약 사용자가 '끝'을 입력하면,
# 반복을 종료합니다. 

# 둘의 선택을 print 해봅니다. 

# 만약 둘이 같은 것을 내면 
# '비겼어요!'를 출력합니다. 
# 아니라면 사용자가 가위인지 판단합니다. 
# 사용자가 가위이면서 컴퓨터가 바위이면 
# '졌어요!'를 출력하고 
# 그렇지 않으면 
# '이겼어요!'를 출력합니다. 

# 같은 원리로 사용자가 바위일 때와

# 보일 때를 짜보세요. 

"가위", "바위","보" 중 하나를 입력해주세요!
("끝"을 입력하면 종료합니다)



입력: 끝



종료합니다.


# Numpy 연습문제

#### 1. Matrix 연산
#### 1-1. 다음과 같은 matrix a, b를 생성하고 서로 곱해보세요

In [109]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
a
b = np.array([[1,2,3],[5,6,7],[9,10,11],[1,2,3]])
b

np.dot(a,b)

array([[ 42,  52,  62],
       [106, 132, 158],
       [170, 212, 254]])

In [106]:
print(a,b, sep ="\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [ 1  2  3]]


#### 1-2. 다음 두 벡터의 내적과 외적 값을 구하세요

In [121]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [124]:
# Your Code Here
print("내적\n" , sum(a*b))
print("외적\n", np.reshape(b,(5,1)) * a)


내적
 130
외적
 [[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [10 20 30 40 50]]


# Pandas

#### 1. dataframe 다루기
#### 1-1. 다음과 같은 dataframe을 생성하세요

In [1]:
import pandas as pd

In [5]:

data = {"조": ["A","A","A","A","A","A","B","B","B","B","B","B","C","C","C","C","C","D","D","D","D","D","E","E","E","E","E"],
        "이름": ["전승우","유응규","박재언","신광욱","박현정","문현주","성민석","이형남","전은정","김아영","남궁찬","고동희","박서호","지현이","윤훈상","양광민","송원호","양태일","하진용","정해원","유승룡","전용진","신하은","조문기","장현정","최준명","이동건"],
        "성별": [1,1,1,1,2,2,1,1,2,2,1,1,1,2,1,1,1,1,1,2,1,1,2,1,2,1,1]}


twelve = pd.DataFrame(data)

In [4]:
twelve

조   이름  성별
0   A  전승우   1
1   A  유응규   1
2   A  박재언   1
3   A  신광욱   1
4   A  박현정   2
5   A  문현주   2
6   B  성민석   1
7   B  이형남   1
8   B  전은정   2
9   B  김아영   2
10  B  남궁찬   1
11  B  고동희   1
12  C  박서호   1
13  C  지현이   2
14  C  윤훈상   1
15  C  양광민   1
16  C  송원호   1
17  D  양태일   1
18  D  하진용   1
19  D  정해원   2
20  D  유승룡   1
21  D  전용진   1
22  E  신하은   2
23  E  조문기   1
24  E  장현정   2
25  E  최준명   1
26  E  이동건   1

#### 1-2. A조 남자와 E조 여자를 출력하세요

In [11]:
twelve[((twelve['조']=='A')&(twelve["성별"] == 1)|(twelve['조']=='E')&(twelve["성별"] == 2))]

조   이름  성별
0   A  전승우   1
1   A  유응규   1
2   A  박재언   1
3   A  신광욱   1
22  E  신하은   2
24  E  장현정   2

#### 1-3. 이씨를 출력하세요 (List 내포 for문을 써서 한줄로 짜보세요 !)

In [12]:
type(twelve['이름'])

pandas.core.series.Series

In [13]:
result = [ name for name in list(twelve['이름']) if name[0] == '이' ]

In [14]:
result

['이형남', '이동건']